import type { Recipe } from "./types";

export const SEED_RECIPES: Recipe[] = [
  {
    id: "seed-herb-roast-chicken",
    slug: "herb-roast-chicken",
    title: "Herb Roast Chicken",
    summary:
      "A Sunday bird with lemon, garlic, and a thicket of thyme — crisp skin, juicy meat, pan drippings worth sopping.",
    ingredients: [
      "1 whole chicken (about 4 lb)",
      "2 lemons, halved",
      "1 head garlic, halved crosswise",
      "1 bunch fresh thyme",
      "4 tbsp unsalted butter, softened",
      "2 tbsp olive oil",
      "Kosher salt and black pepper",
      "1 large yellow onion, thickly sliced",
    ],
    steps: [
      "Heat the oven to 425°F. Pat the chicken dry and season generously inside and out with salt and pepper.",
      "Stuff the cavity with lemon halves, garlic, and most of the thyme. Rub the skin with softened butter.",
      "Scatter onion in a roasting pan, set the chicken on top, and drizzle with olive oil.",
      "Roast 55–70 minutes until the thickest part of the thigh hits 165°F. Rest 15 minutes before carving.",
      "Spoon pan juices over the meat and finish with a squeeze of roasted lemon.",
    ],
    tags: ["dinner", "roast", "sunday"],
    prepMinutes: 20,
    cookMinutes: 70,
    servings: 4,
    imageUrl:
      "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Golden roast chicken on a platter with herbs",
    authorId: "system",
    authorName: "Gregg's Kitchen",
    source: "local",
    updatedAt: "2026-03-01T12:00:00.000Z",
  },
  {
    id: "seed-weeknight-carbonara",
    slug: "weeknight-carbonara",
    title: "Weeknight Carbonara",
    summary:
      "Eggs, pecorino, and crisp guanciale — no cream, just emulsified silk that clings to every strand.",
    ingredients: [
      "12 oz spaghetti or bucatini",
      "4 oz guanciale or pancetta, diced",
      "3 large eggs + 1 yolk",
      "1 cup finely grated pecorino Romano",
      "Freshly cracked black pepper",
      "Kosher salt",
    ],
    steps: [
      "Boil pasta in well-salted water until just shy of al dente. Reserve 1 cup pasta water.",
      "Render guanciale in a wide skillet over medium heat until crisp; keep the fat.",
      "Whisk eggs, yolk, pecorino, and plenty of pepper in a bowl.",
      "Off heat, toss drained pasta into the skillet with a splash of pasta water.",
      "Quickly stir in the egg mixture, adding pasta water until glossy. Serve immediately.",
    ],
    tags: ["pasta", "quick", "italian"],
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 3,
    imageUrl: "",
    imageAlt: "",
    authorId: "system",
    authorName: "Gregg's Kitchen",
    source: "local",
    updatedAt: "2026-03-04T12:00:00.000Z",
  },
  {
    id: "seed-citrus-olive-oil-cake",
    slug: "citrus-olive-oil-cake",
    title: "Citrus Olive Oil Cake",
    summary:
      "Moist, fragrant, and barely sweet — orange zest and good olive oil for an afternoon slice with coffee.",
    ingredients: [
      "1 1/2 cups all-purpose flour",
      "1 cup sugar",
      "1/2 tsp baking powder",
      "1/2 tsp baking soda",
      "1/2 tsp kosher salt",
      "3 large eggs",
      "3/4 cup extra-virgin olive oil",
      "3/4 cup whole milk",
      "Zest of 2 oranges",
      "1/4 cup fresh orange juice",
      "1 tsp vanilla extract",
    ],
    steps: [
      "Heat oven to 350°F. Butter a 9-inch cake pan and line the bottom with parchment.",
      "Whisk flour, sugar, baking powder, baking soda, and salt.",
      "In another bowl, whisk eggs, olive oil, milk, zest, juice, and vanilla.",
      "Fold wet into dry until just combined. Pour into the pan.",
      "Bake 35–40 minutes until a tester comes out clean. Cool before slicing.",
    ],
    tags: ["dessert", "baking", "citrus"],
    prepMinutes: 15,
    cookMinutes: 40,
    servings: 8,
    imageUrl: "",
    imageAlt: "",
    authorId: "system",
    authorName: "Gregg's Kitchen",
    source: "local",
    updatedAt: "2026-03-08T12:00:00.000Z",
  },
  {
    id: "seed-smoky-black-bean-chili",
    slug: "smoky-black-bean-chili",
    title: "Smoky Black Bean Chili",
    summary:
      "Deep chipotle heat, cocoa for body, and a squeeze of lime — weeknight stew that tastes like it simmered all day.",
    ingredients: [
      "2 tbsp olive oil",
      "1 large onion, diced",
      "1 red bell pepper, diced",
      "4 garlic cloves, minced",
      "2 tbsp chili powder",
      "1 tsp ground cumin",
      "1 tsp smoked paprika",
      "1 chipotle in adobo, minced + 1 tbsp sauce",
      "1 tbsp unsweetened cocoa powder",
      "2 cans (15 oz) black beans, drained",
      "1 can (28 oz) crushed tomatoes",
      "1 cup vegetable broth",
      "Kosher salt, lime wedges, cilantro to serve",
    ],
    steps: [
      "Warm oil in a heavy pot. Soften onion and pepper 8 minutes; add garlic for 1 minute.",
      "Stir in spices, chipotle, and cocoa until fragrant.",
      "Add beans, tomatoes, and broth. Simmer gently 25–30 minutes.",
      "Season with salt. Finish with lime and cilantro. Serve with rice or cornbread.",
    ],
    tags: ["vegetarian", "soup", "weeknight"],
    prepMinutes: 15,
    cookMinutes: 35,
    servings: 6,
    imageUrl: "",
    imageAlt: "",
    authorId: "system",
    authorName: "Gregg's Kitchen",
    source: "local",
    updatedAt: "2026-03-10T12:00:00.000Z",
  },
  {
    id: "seed-miso-butter-salmon",
    slug: "miso-butter-salmon",
    title: "Miso Butter Salmon",
    summary:
      "Fifteen minutes from skillet to plate — white miso, butter, and a whisper of honey on crisp-skinned fillets.",
    ingredients: [
      "4 salmon fillets (6 oz each), skin on",
      "2 tbsp white miso",
      "2 tbsp unsalted butter, softened",
      "1 tsp honey",
      "1 tsp rice vinegar",
      "Neutral oil for the pan",
      "Scallions and sesame seeds to finish",
      "Steamed rice, for serving",
    ],
    steps: [
      "Mix miso, butter, honey, and vinegar into a paste.",
      "Pat salmon dry and season lightly with salt. Heat a slick of oil in a skillet over medium-high.",
      "Cook skin-side down 4–5 minutes until crisp. Flip, spread miso butter on top, and cook 2–3 minutes more.",
      "Rest briefly. Scatter scallions and sesame; serve over rice.",
    ],
    tags: ["seafood", "quick", "dinner"],
    prepMinutes: 10,
    cookMinutes: 12,
    servings: 4,
    imageUrl:
      "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1600&q=80",
    imageAlt: "Pan-seared salmon fillet with greens",
    authorId: "system",
    authorName: "Gregg's Kitchen",
    source: "local",
    updatedAt: "2026-03-12T12:00:00.000Z",
  },
];
